services:
  next-app:
    container_name: Next-HRT
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "5844:5844"
    volumes:
      - /hrt/uploads:/app/uploads
      - /hrt/prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
